language: c

sudo: false

matrix:
  include:
    - os: linux
      compiler: gcc
      install: bash .ci/build-c2man.sh
      env: PATH=$PATH:$TRAVIS_BUILD_DIR/c2man-install
    - os: linux
      compiler: clang
      env: DISTCHECK_CONFIGURE_FLAGS=--disable-docs
    - os: osx
      compiler: clang
      env: DISTCHECK_CONFIGURE_FLAGS=--disable-docs

before_script:
  - ./autogen.sh $DISTCHECK_CONFIGURE_FLAGS

script:
  - make
  - make check || (cat */test-suite.log && false)
  - make distcheck || (cat */test-suite.log && false)
